### ISSUE TITLE
Open Issue and Pull Requests - who wants 'em?

### ISSUE THREAD

**Issue by kaoru** [lokku/Css-SpriteMaker#7]
CC @darksmo @freyfogle @jrgomezgar 

Looks like this repository and module are getting a little stale 🍞 

**Juan:** is Mitula Group still using/wanting to maintain CSS::SpriteMaker?

_If no can we get it transferred off the lokku Github account?_

**Ed:** are you using it for any of your projects?

_If yes, do you or MTM want to take over maintenance?_

**Savio:** are you still interested in maintaining it?

_If not, do you mind if I take over?_

-------

Thanks!

Alex

**Comment by darksmo** [comment]
Hey Alex, in my view the module was developed at Lokku, with myself as author. Therefore I think it's up to the Mitula group to decide what to do with it. I like the idea of keeping it in the Lokku account in the end. It's where it belong and brings me good memories. However, if this **has** to go off the Lokku account, and there is no other place where we can all contribute with equal "political" rights, it should perhaps go back to the author, and have "official" maintainers, if any, as collaborators.

**Comment by freyfogle** [comment]
I've always advocated that sprites should be made by hand, not software! Usually what I do it print out the various images, cut them out and then tape them all to a single poster board which I then take a picture of to create the new image. It's a bit slower perhaps, but if the only way to really give me pixel level control of the final image.

What I'm saying is, I don't use this software in any way. I wish it well wherever fate may take it.

**Comment by kaoru** [comment]
You're the man @darksmo! If you're still happy owning it and maintaining it I certainly won't take that away from you, just wanted to offer to adopt in case you had moved on :-) In that case I think it can stay right where it is!
